### ISSUE TITLE
Crash on clicking channel in oscilloscope

### ISSUE THREAD

**Issue by torebutlin** [torebutlin/cued_datalogger#8]
Python crashes when clicking on channel in oscilloscope view

**Comment by ghost** [comment]
Wow. This is a weird error.

**Comment by torebutlin** [comment]
Error message from debug version below. Is this repeatable on other pc's?

Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\cued_datalogger\acquisition\acquisition_window.py", line 324, in display_chan_config
    self.chanconfig_UI.chans_num_box.setCurrentIndex(num)
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'NoneType'

**Comment by ghost** [comment]
I got exactly the same error
